### ISSUE TITLE
[REVIEW] How it Works / Radicle Link Documentation

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#9]
For the Link team — I'm often asked for an "explainer" or "protocol spec" regarding radicle-link design. Right now, I simply refer people to the [How it Works blog post](https://radicle.xyz/radicle-link.html) that we have up on the old website.

Do we have an updated spec or more comprehensive documentation on how Link works? If so, I'd like to support with getting this documentation pushed to radicle-docs and/or somewhere clear in the radicle-link repo.

Tagging you all as you're who came to mind here — feel free to offer suggestions & feedback on what we should do and who should do it.

**Comment by FintanH** [comment]
There are three existing documents:

1. https://github.com/radicle-dev/radicle-link/blob/master/spec/out/radicle-link.pdf -- this was the first spec proposed. Some of the details are implemented, some of them are outdated. Probably not useful to link the document directly to others since some of the outdated details may lead to confusion.
2. https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/identity_resolution.md -- this is implemented and (mostly?) up to date. It outlines the monorepo structure amongst other things. Very useful for understanding the ideas behind how we're using git as a database.
3. https://github.com/radicle-dev/radicle-link/blob/master/docs/spec/identities.md -- this is implemented but not integrated. This outlines what the future of identity documents will be and how they will be verified.
